### ISSUE TITLE
Produce documentation outlining the target approach to generating CSVW.

### ISSUE THREAD

**Issue by rossbowen** [GSS-Cogs/sprint-planning#10]
- [ ] Describe the inputs required from users (whether that be DMs or external users).
- [ ] Describe any transformations of those inputs which take place.
- [ ] Describing the mapping of those inputs to the output CSVW.
- [ ] Describe the output CSVW.

This can be shared with Swirrl and should meet some needs in describing the starting point of the current DM workflow.

**Comment by rossbowen** [comment]
Related:
[Dimensions with codelists which use concepts from multiple namespaces are difficult to create and manage #210](https://github.com/GSS-Cogs/gss-utils/issues/210).

**Comment by rossbowen** [comment]
Initial writings [here](https://github.com/GSS-Cogs/csvwlib/wiki/Cubes), will continue to adapt these as work into new CSVW tooling progresses.

**Comment by rossbowen** [comment]
Ongoing writing occurring as part of the [`linked-data-book`](https://github.com/GSS-Cogs/linked-data-book) repo.
