### ISSUE TITLE
Large Datasets

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/sprint-planning#19]
- [ ] Determine how data loading speed corresponds to size of datasets & metrics on how large is large.
- [ ] Use an example large dataset to try out multi-graph dataset functionality.
- [ ] Test functionality to partially update large datasets by adding new data or even deleting some data.

**Comment by canwaf** [comment]
Through https://github.com/GSS-Cogs/pmd-jenkins-library/issues/66 for the Jenkins changes, and https://github.com/GSS-Cogs/family-trade/issues/14 and https://github.com/GSS-Cogs/family-trade/issues/12 for the datasets, we will have a good play on multi-graph dataset functionality and identify issues which come from the implementation of the multi-graph dataset.

Adding and deleting new data will also be considered.
