### ISSUE TITLE
Fix URI templates

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/sprint-planning#20]
- [x] HMRC Regional Trade Statistics
- [x] [ONS Quarterly Country and Regional GDP](https://github.com/GSS-Cogs/family-trade/issues/85#issuecomment-840432501)
- [x] HMRC Overseas Trade Statistics
- [x] ONS International trade in services by subnational areas of the UK
- [x] ONS International exports of services from subnational areas of the UK
- [x] HMRC RTS Small Area NUTS codes with / chars GSS-Cogs/gss-utils#258

**Comment by canwaf** [comment]
Marked OTS and RTS as complete.

**Comment by JasonHowell** [comment]
Closing this issue as the ticket list has been completed above.
