### ISSUE TITLE
Continuous Data Integration

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/sprint-planning#32]
As we scale up and have ever more processes and data processing with diverse dependencies between different processes, we need to look at standard practices for dealing with continuous integration/delivery and how these can be applied to data processing workflows.

- [x] Continuous Integration with fixtures in trade pipelines: GSS-Cogs/family-trade#196
- [x] De-couple live web resources as fixtures: GSS-Cogs/gss-utils#196
- [x] JUnit reports from csvlint.
- [x] Investigate GitHub Checks API and Jenkins plugin to report on issues in branches. See https://github.com/jenkinsci/checks-api-plugin/blob/master/docs/implementation-guide.md
