### ISSUE TITLE
Tabulated Data

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/sprint-planning#9]
- [x] Consider multi-measure display options.
- [x] Investigate & determine ways to deliver data in tabular form. (e.g. cross tabulation, wide)

Later
- [ ] Implement technical solution

**Comment by rossbowen** [comment]
@robons prototype: 
https://github.com/robons/sparql-qb-pivot-test-ui

Some discussion here.
https://onswebsite.slack.com/archives/CP78UD9LZ/p1614762538002600

**Comment by roblinksdata** [comment]
You can find an updated and live version of my demo at <https://robons.github.io/sparql-qb-pivot-test-ui/index.html>

I've added a dropdown so you can switch between the datasets.

Make sure you're aware of query caching. Most datasets typically take >8 seconds to load one page of data.

**Comment by martinpj-ons** [comment]
Swirrl looking to investigate this to provide options 4 or 5 in his document https://docs.google.com/presentation/d/12BdkcnG_wvmdiEYJTzVqLk5M2bK1etsdh26Xzf18Q48/edit

He will then get us to review before implementing See https://github.com/Swirrl/cogs-issues/issues/315
